// <auto-generated />
namespace DBase.EntityFrameWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tables_UserInfo_UserCredential : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tables_UserInfo_UserCredential));
        
        string IMigrationMetadata.Id
        {
            get { return "201804072050188_Tables_UserInfo_UserCredential"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
